# Generated by Django 5.0.3 on 2025-06-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_user_current_token_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light Theme'), ('bw', 'Black & White Theme'), ('dark', 'Dark Theme')], default='light', max_length=10),
        ),
    ]
