# Generated by Django 5.0.3 on 2025-06-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_user_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('dark', 'Dark Theme'), ('bw', 'Black & White Theme'), ('light', 'Light Theme')], default='dark', max_length=10),
        ),
    ]
