# Generated by Django 5.1.3 on 2025-05-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0012_salesproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesproduct',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='salesproduct',
            name='price',
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (e.g., 10 for 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Final price after discount (auto-calculated)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original price before any discounts', max_digits=10),
            preserve_default=False,
        ),
    ]
