# Generated by Django 5.1.3 on 2025-05-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0013_remove_salesproduct_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesproduct',
            name='discount_percent',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Discount percentage (e.g., 10 for 10%)', max_digits=5),
        ),
    ]
