# Generated by Django 5.1.3 on 2025-06-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0014_alter_salesproduct_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
