# Generated by Django 5.1.3 on 2025-06-01 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0016_order_orderdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order Detail', 'verbose_name_plural': 'Order Details'},
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='my_ecommerce.order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='my_ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units ordered'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, help_text='Automatically calculated as unit_price * quantity', null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='unit_price',
            field=models.PositiveBigIntegerField(help_text='Price per unit at the time of purchase'),
        ),
    ]
