# Generated by Django 5.1.3 on 2025-06-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0019_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
