# Generated by Django 5.1.3 on 2025-06-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0020_alter_order_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='product_id',
        ),
    ]
