# Generated by Django 5.1.3 on 2025-06-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0021_rename_product_orderdetail_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_id',
            new_name='product',
        ),
    ]
