# Generated by Django 5.1.3 on 2025-06-02 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0022_rename_product_id_orderdetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='sale_product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details1', to='my_ecommerce.salesproduct'),
        ),
    ]
