# Generated by Django 5.1.3 on 2025-06-02 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0023_orderdetail_sale_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='sale_product_id',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='sales_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='my_ecommerce.salesproduct'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='my_ecommerce.product'),
        ),
    ]
