# Generated by Django 5.1.3 on 2025-06-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0026_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=20, null=True),
        ),
    ]
