# Generated by Django 5.0.3 on 2025-06-18 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0033_productimage_created_by_productimage_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sale_product_images/')),
                ('alt_text', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saleproductimage_created_by', to=settings.AUTH_USER_MODEL)),
                ('sale_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='my_ecommerce.salesproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saleproductimage_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
