# Generated by Django 5.0.3 on 2025-06-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0034_salesproductimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesproductimage',
            old_name='image',
            new_name='images',
        ),
    ]
