# Generated by Django 5.0.3 on 2025-06-27 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce', '0038_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_input', message='This field accepts only alphabetic characters and single spaces between words.', regex='^[a-zA-Z]+( [a-zA-Z]+)*$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number can only contain digits, spaces, dashes (-), parentheses (), and plus (+).', regex='^[\\d\\-\\+\\(\\) ]+$')]),
        ),
    ]
